import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

type ReadinessFailure = {
  file: string;
  message: string;
};

export type ReadinessEvidence = {
  id: string;
  requirement: string;
  evidence: string;
  status: "pass" | "fail";
  failures: ReadinessFailure[];
};

type PackageJson = {
  scripts?: Record<string, string>;
};

export function checkAgentReadinessProject(root = process.cwd()): ReadinessFailure[] {
  const failures: ReadinessFailure[] = [];
  const packageJson = readJson<PackageJson>(root, "package.json", failures);
  const scripts = packageJson?.scripts ?? {};

  requireScript(failures, scripts, "check", "tsc --noEmit");
  requireScript(failures, scripts, "compare:gate", "scripts/check-comparison-gates.ts");
  requireScript(failures, scripts, "compare:static:fixtures:gate", "scripts/check-fixture-static-gate.ts");
  requireScript(failures, scripts, "check:processes", "scripts/check-project-processes.ts");
  requireScript(failures, scripts, "readiness:audit", "scripts/check-agent-readiness.ts");
  requireScript(failures, scripts, "readiness:real-page-smoke", "scripts/check-real-page-smoke.ts");
  requireScript(failures, scripts, "readiness:agent-browser-smoke", "scripts/check-agent-browser-smoke.ts");

  requireFileIncludes(root, failures, "vitest.config.ts", [
    "fileParallelism: false",
    "maxWorkers: 1",
  ]);
  requireFileIncludes(root, failures, "AGENTS.md", [
    "Do not run project tests, comparison scripts, or browser-backed checks in\n  parallel",
    "After any browser-backed command, verify that no project-owned browser or\n  `agent-browser` process was left behind",
  ]);
  requireFileIncludes(root, failures, "docs/benchmarks.md", [
    "pnpm compare:static:fixtures:gate",
    "pnpm check:processes",
    "uses synthetic\nHTML fixtures only",
  ]);
  requireFileIncludes(root, failures, "docs/comparison-baseline.md", [
    "Operational rule: run comparison suites sequentially",
    "averageCliAgentScore",
    "minCliAgentScore",
    "weakAgentTargets",
    "averageAgentExecutorScore",
    "minAgentExecutorScore",
    "averageAgentTopReadTargetShortcutScore",
    "averageAgentFormActionCountScore",
    "averageAgentChoiceCountScore",
    "averageAgentTopChoiceShortcutScore",
    "averageAgentTopResultChoiceShortcutScore",
    "averageAgentTopCitationShortcutScore",
    "averageAgentEvidenceCountShortcutScore",
    "averageAgentSignalCountShortcutScore",
    "averageAgentTopQualityShortcutScore",
    "averageAgentProblemShortcutScore",
    "averageAgentExecutorShortcutScore",
    "averageAgentHandoffShortcutScore",
    "averageAgentAnswerShortcutScore",
    "averageAgentTopActionShortcutScore",
    "averageAgentFormActionChoiceScore",
    "averageAgentVerificationQueryScore",
    "averageAgentSourceSearchShortcutScore",
    "averageAgentHiddenSignalScore",
    "averageAgentHiddenSignalCountScore",
    "averageAgentTopHiddenSignalShortcutScore",
    "averageAgentHiddenCommandShortcutScore",
    "averageAgentPageMetadataShortcutScore",
    "averageAgentBrowserHtmlScore",
  ]);
  requireFileIncludes(root, failures, "docs/agent-readiness.md", [
    "Do not call this objective complete from unit tests alone",
    "Browser-backed comparison suites must run sequentially",
    "process cleanup before and after browser-backed comparison commands",
  ]);
  requireFileIncludes(root, failures, "scripts/check-fixture-static-gate.ts", [
    "agent-fixtures",
    "runStaticComparisons",
    "checkComparisonGateReport",
  ]);
  requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
    "agent-fixtures",
    "!warning.includes(\"agent-browser\")",
    "checkComparisonGateReport(report)",
  ]);
  requireFileIncludes(root, failures, "tests/process-check.test.ts", [
    "findProjectProcesses",
    "agent-browser",
    "pnpm compare:static:fixtures:gate",
  ]);

  checkReadmeSplit(root, failures);
  for (const evidence of collectAgentReadinessEvidence(root)) {
    if (evidence.status === "pass") continue;
    for (const failure of evidence.failures) {
      failures.push({
        file: failure.file,
        message: `[${evidence.id}] ${failure.message}`,
      });
    }
  }

  return failures;
}

export function collectAgentReadinessEvidence(root = process.cwd()): ReadinessEvidence[] {
  return [
    evidenceCheck(
      root,
      "resource-safety",
      "Project validation must run with concurrency 1 and leave no project browser/test processes behind.",
      "AGENTS.md, vitest.config.ts, docs, and pnpm check:processes encode the operational safety rule.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "check:processes", "scripts/check-project-processes.ts");
        requireFileIncludes(root, failures, "vitest.config.ts", ["fileParallelism: false", "maxWorkers: 1"]);
        requireFileIncludes(root, failures, "AGENTS.md", [
          "Do not run project tests, comparison scripts, or browser-backed checks in\n  parallel",
          "After any browser-backed command, verify that no project-owned browser or\n  `agent-browser` process was left behind",
        ]);
        requireFileIncludes(root, failures, "docs/benchmarks.md", ["pnpm check:processes"]);
      },
    ),
    evidenceCheck(
      root,
      "browser-session-cleanup",
      "Browser-backed comparison scripts must serialize `agent-browser` use and close sessions on failure paths.",
      "compare.ts and compare-static.ts use a shared lock pattern plus finally-based session close helpers.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/compare.ts", [
          "withAgentBrowserLock",
          "closeAgentBrowserSession",
          "finally",
          "\"close\"",
        ]);
        requireFileIncludes(root, failures, "scripts/compare-static.ts", [
          "withAgentBrowserLock",
          "closeAgentBrowserSession",
          "finally",
          "\"close\"",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "fixture-loop-coverage",
      "Search and page-check agent loops must be covered without starting browsers or remote fetches.",
      "The fixture gate uses synthetic HTML targets for search open/refine, site search, hidden metadata, Web Components, actions, and browser HTML retry.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/benchmark-targets.ts", [
          "Synthetic search open gate",
          "Synthetic search refine gate",
          "Synthetic site search recovery gate",
          "Synthetic hidden metadata gate",
          "Synthetic web component gate",
          "Synthetic action target gate",
          "Synthetic browser HTML retry gate",
        ]);
        requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
          "open-result",
          "refine-search",
          "open-site-search",
          "Synthetic web component gate",
          "retry-with-browser-html",
          "!warning.includes(\"agent-browser\")",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "real-page-smoke",
      "At least one real page must prove static agent handoff without `agent-browser` before claiming browser parity progress.",
      "readiness:real-page-smoke checks https://example.com with --agent-brief, no Puppeteer, and no agent-browser process.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:real-page-smoke", "scripts/check-real-page-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-real-page-smoke.ts", [
          "https://example.com",
          "--agent-brief",
          "needsBrowserHtml",
          "canUseFetchedHtml",
          "semanticNamedRoleCount",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "declarative-shadow-static",
      "Static extraction must preserve useful declarative shadow DOM controls without keeping inert template payloads.",
      "Static extractor and tests cover shadowrootmode templates, custom-element wrapper pruning, and normal template pruning.",
      (failures) => {
        requireFileIncludes(root, failures, "src/static.ts", [
          "isDeclarativeShadowTemplate",
          "shadowrootmode",
          "shouldPruneCustomElementWrapper",
        ]);
        requireFileIncludes(root, failures, "tests/static.test.ts", [
          "extracts declarative shadow DOM children while pruning inert templates",
          "projects declarative shadow DOM slots instead of duplicating light DOM",
          "<template shadowrootmode=\"open\">",
          "Slotted text action",
          "Slotted field label",
          "Slotted for-label",
          "Host action",
          "Host help",
          "Template payload",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "keeps declarative shadow DOM controls in agent brief handoff",
          "projects declarative shadow DOM slots in agent brief handoff",
          "uses slotted text for declarative shadow DOM accessible names",
          "uses slotted IDREF labels for declarative shadow DOM fields",
          "uses slotted label-for text for declarative shadow DOM fields",
          "uses projected slot text for declarative shadow DOM host action names",
          "semanticTopButtonDescription",
          "semanticTopButtonControlsTargetSelector",
          "semanticTopFieldLabelledBySelector",
          "Shadow details",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "agent-browser-smoke",
      "At least one bounded `agent-browser` comparison must prove static named-role parity before the goal can move beyond local and fetched-page smoke evidence.",
      "readiness:agent-browser-smoke runs pnpm compare on https://example.com, https://books.toscrape.com/, https://news.ycombinator.com, and https://www.gov.uk/foreign-travel-advice with per-target floors.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:agent-browser-smoke", "scripts/check-agent-browser-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-agent-browser-smoke.ts", [
          "https://example.com",
          "https://books.toscrape.com/",
          "https://news.ycombinator.com",
          "https://www.gov.uk/foreign-travel-advice",
          "pnpm",
          "compare",
          "agentBrowser",
          "overlap",
          "agentReadiness",
          "minReadinessScore",
        ]);
        requireFileIncludes(root, failures, "scripts/check-project-processes.ts", [
          "scripts\\/compare\\.ts",
          "pnpm\\s+compare",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "agent-browser-text-heavy-smoke",
      "Text-heavy document pages must not be judged only by raw StaticText volume when action, navigation, and structural content parity are usable.",
      "readiness:agent-browser-text-heavy-smoke runs pnpm compare on Korean Wikipedia and enforces structuralContentRecall and textRecall reporting separately.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:agent-browser-text-heavy-smoke", "scripts/check-agent-browser-text-heavy-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-agent-browser-text-heavy-smoke.ts", [
          "https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD",
          "pnpm",
          "compare",
          "structuralContentRecall",
          "textRecall",
          "agentReadiness",
          "agentBrowser",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "per-target-gates",
      "No included target may hide behind good averages when agent output is too weak.",
      "Static comparison gates enforce per-target CLI and executor floors in addition to average scores.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/check-comparison-gates.ts", [
          "minCliAgentScore",
          "minAgentExecutorScore",
          "averageCliAgentScore",
          "averageAgentExecutorScore",
          "averageAgentTopReadTargetShortcutScore",
          "averageAgentFormActionChoiceScore",
          "averageAgentChoiceCountScore",
          "averageAgentTopChoiceShortcutScore",
          "averageAgentTopResultChoiceShortcutScore",
          "averageAgentTopCitationShortcutScore",
          "averageAgentEvidenceCountShortcutScore",
          "averageAgentSignalCountShortcutScore",
          "averageAgentProblemShortcutScore",
          "averageAgentExecutorShortcutScore",
          "averageAgentHandoffShortcutScore",
          "averageAgentAnswerShortcutScore",
          "averageAgentTopActionShortcutScore",
          "averageAgentVerificationQueryScore",
          "averageAgentSourceSearchShortcutScore",
          "averageAgentTopReadTargetShortcutScore",
          "averageAgentTopActionShortcutScore",
        ]);
        requireFileIncludes(root, failures, "scripts/compare-static.ts", [
          "sourceSearchSelectedCommandArgs",
          "sourceSearchFailureCommandArgs",
          "sourceSearchAlternateCommandArgs",
          "typeof link.command === \"string\"",
          "link.command.length > 0",
          "typeof item.command === \"string\"",
          "item.command.length > 0",
          "choice.command === expected.command",
          "agentChoice?.command === choice.command",
          "function hasExecutableCommand",
          "handoff.resultChoices.some(hasExecutableCommand)",
          "topFormChoiceCommand",
          "topActionTargetChoiceCommand",
          "executorBrowserHtmlReasonCode",
          "handoffBrowserHtmlReasonCode",
          "executorReadValueReferencePath",
          "handoffReadValueReferencePath",
          "runbookReadValueReferencePath",
        ]);
        requireFileIncludes(root, failures, "src/cli.ts", [
          "compactAgentSourceSearchResultList(handoff.resultChoices.map",
          "compactAgentSourceSearchResultList(resultChoices.map",
          "compactAgentSitelinks",
          "choice.command ? { command: choice.command }",
          "topFormChoiceCommand",
          "topActionTargetChoiceCommand",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "adds executable commands to site-search form choices when find text is missing",
          "prints executable form choice commands in text output",
          "prints executable action-target commands in text output",
          "topFormChoiceCommandArgs",
          "topActionTargetChoiceCommandArgs",
          "executorBrowserHtmlCommand:",
          "handoffBrowserHtmlCommand:",
        ]);
        requireFileIncludes(root, failures, "docs/comparison-baseline.md", [
          "minCliAgentScore",
          "minAgentExecutorScore",
          "averageAgentFormActionChoiceScore",
          "averageAgentChoiceCountScore",
          "averageAgentTopChoiceShortcutScore",
          "averageAgentTopCitationShortcutScore",
          "averageAgentEvidenceCountShortcutScore",
          "averageAgentSignalCountShortcutScore",
          "averageAgentProblemShortcutScore",
          "averageAgentExecutorShortcutScore",
          "averageAgentHandoffShortcutScore",
          "averageAgentAnswerShortcutScore",
          "averageAgentVerificationQueryScore",
          "averageAgentSourceSearchShortcutScore",
          "averageAgentBrowserHtmlScore",
          "sourceSearchSelectedCommandArgs",
          "sourceSearchAlternateCommandArgs",
          "agent.handoff",
          "agent.executor",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "weak-target-diagnostics",
      "When a target fails the floor, the report must name the weak target and its agent status/action.",
      "compare:gate emits weakAgentTargets with category, URL, scores, status, and primary action.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/check-comparison-gates.ts", [
          "weakAgentTargets",
          "weakAgentTarget",
          "primaryAction",
          "agentStatus",
        ]);
        requireFileIncludes(root, failures, "tests/comparison-gate.test.ts", [
          "weakAgentTarget",
          "minCliAgentScore",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "executable-agent-continuations",
      "Subagents must receive executable next commands for search, source, form, action-target, and browser-retry loops.",
      "CLI tests and fixture gates cover commandArgs/result/source choices, page actions, and browser HTML retry actions.",
      (failures) => {
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "resultChoices",
          "topResultChoicePath",
          "topResultChoiceHost",
          "topResultChoiceUrlPath",
          "topResultChoiceCommandArgs",
          "topResultChoiceSourceType",
          "topResultChoiceSourceScore",
          "topResultChoiceSourceHints",
          "topResultChoiceDateText",
          "topResultChoiceDateIso",
          "topResultChoiceDateUnixMs",
          "topChoiceDateIso",
          "topChoiceDateUnixMs",
          "recommendedDateIso",
          "recommendedDateUnixMs",
          "searchDecisionRecommendedDateIso",
          "searchDecisionRecommendedDateUnixMs",
          "topResultChoiceRelevance",
          "topResultChoiceMatchedTerm",
          "topResultChoiceFindMatch",
          "topResultChoiceLikelyOfficial",
          "topResultChoiceSitelinkCount",
          "topResultChoiceFirstSitelinkTitle",
          "topResultChoiceFirstSitelinkUrl",
          "topResultChoiceFirstSitelinkCommand",
          "topResultChoiceFirstSitelinkCommandArgs",
          "commandArgs",
          "sourceLinkRef",
          "formChoices",
          "actionTargetChoices",
          "executor",
          "handoff",
          "forms",
          "actionTargets",
        ]);
        requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
          "agentPrimaryAction",
          "retry-with-browser-html",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "count-shortcuts",
      "Agent output must expose quick count shortcuts so subagents can judge page richness without parsing nested arrays.",
      "Agent summaries and text output expose result, evidence, form/action, hidden-signal, read-target, and source-link counts.",
      (failures) => {
        requireFileIncludes(root, failures, "src/types.ts", [
          "resultCount",
          "resultChoiceCount",
          "formCount",
          "formChoiceCount",
          "formChoices",
          "topFormChoicePath",
          "topFormChoiceUrlTemplate",
          "topFormChoiceQueryField",
          "topFormChoiceSubmitText",
          "topFormChoiceFirstFieldName",
          "topFormChoiceFirstFieldType",
          "topFormChoiceFirstFieldLabel",
          "topFormChoiceFirstFieldPlaceholder",
          "topFormChoiceFirstFieldAutocomplete",
          "topFormChoiceFirstFieldPattern",
          "topFormChoiceFirstFieldRequired",
          "topFormChoiceFirstFieldInvalid",
          "topFormChoiceFirstFieldSelector",
          "topFormChoiceRequiredFieldName",
          "topFormChoiceRequiredFieldType",
          "topFormChoiceRequiredFieldLabel",
          "topFormChoiceRequiredFieldRequired",
          "topFormChoiceRequiredFieldSelector",
          "topFormChoiceInvalidFieldName",
          "topFormChoiceInvalidFieldInvalid",
          "topFormChoiceInvalidFieldSelector",
          "actionTargetCount",
          "actionTargetChoiceCount",
          "actionTargetChoices",
          "topActionTargetChoicePath",
          "topActionTargetChoiceName",
          "topActionTargetChoiceKind",
          "topActionTargetChoiceSource",
          "topActionTargetChoiceUrlTemplate",
          "topActionTargetChoiceUrlTemplatePath",
          "topActionTargetChoiceUrlTemplateQuery",
          "topActionTargetChoiceQueryInput",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchFindQueryCount",
          "sourceSearchTopFindQuery",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchSelectedSourceType",
          "sourceSearchSelectedSourceHints",
          "sourceSearchSelectedDateIso",
          "sourceSearchSelectedDateUnixMs",
          "sourceSearchFailurePath",
          "sourceSearchFailureHost",
          "sourceSearchFailureCommandArgs",
          "sourceSearchAlternateCount",
          "sourceSearchAlternateSourceType",
          "sourceSearchAlternateSourceHints",
          "sourceSearchAlternateDateIso",
          "sourceSearchAlternateDateUnixMs",
          "sourceSearchAlternateDifferentHost",
          "needsBrowserInteraction",
          "hiddenSignalCount",
          "hiddenReadTargetCount",
          "topHiddenSignalPath",
          "topHiddenSignalText",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "sourceLinkCount",
          "sourceChoiceCount",
          "topSourceChoicePath",
          "topSourceChoiceUrl",
          "topSourceChoiceHost",
          "topSourceChoiceUrlPath",
          "topSourceChoiceCommandArgs",
          "topSourceChoiceSourceType",
          "topSourceChoiceSourceHints",
          "topChoiceKind",
          "topChoicePath",
          "topChoiceCommandArgs",
          "topChoiceUrlPath",
          "topChoiceUrlQuery",
          "topActionTargetUrlPath",
          "topActionTargetUrlQuery",
          "topChoiceRequiredFieldName",
          "topChoiceInvalidFieldInvalid",
          "recommendedCommandArgs",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "topBarrierText",
          "dataTableCount",
          "faqCount",
          "codeBlockCount",
          "resourceCount",
          "mediaCount",
          "sectionCount",
          "breadcrumbCount",
          "paginationCount",
          "tocCount",
          "embedCount",
          "transcriptCount",
          "authorLinkCount",
          "provenanceCount",
          "offerCount",
          "datasetCount",
          "identityCount",
          "timelineCount",
          "contactPointCount",
          "topDataTablePath",
          "topDataTableHeaders",
          "topDataTableSecondRow",
          "topDataTableSecondCell",
          "topFaqQuestion",
          "topCodeBlockText",
          "topResourceUrl",
          "topResourceCommandArgs",
          "topMediaUrl",
          "topMediaCommandArgs",
          "topSectionPath",
          "topSectionHeading",
          "topSectionLevel",
          "topBreadcrumbText",
          "topPaginationPath",
          "topPaginationUrl",
          "topPaginationCommandArgs",
          "topTocPath",
          "topTocText",
          "topTocFirstItemLabel",
          "topTocFirstItemCommandArgs",
          "topEmbedUrl",
          "topEmbedCommandArgs",
          "topTranscriptUrl",
          "topTranscriptCommandArgs",
          "topAuthorLinkUrl",
          "topAuthorLinkCommandArgs",
          "topProvenancePath",
          "topProvenanceValue",
          "topProvenanceCommandArgs",
          "topOfferPath",
          "topOfferPrice",
          "topOfferPriceAmount",
          "topOfferCommandArgs",
          "topDatasetPath",
          "topDatasetCommandArgs",
          "topDatasetDistributionCommandArgs",
          "topDatasetLicenseUrl",
          "topDatasetLicenseCommandArgs",
          "topDatasetTemporalCoverage",
          "topDatasetSpatialCoverage",
          "topDatasetCreator",
          "topIdentityPath",
          "topIdentityName",
          "topIdentityCommandArgs",
          "topIdentitySameAsCommandArgs",
          "topTimelinePath",
          "topTimelineValue",
          "topTimelineIsoDate",
          "topTimelineUnixMs",
          "topContactPointPath",
          "topContactPointValue",
          "structuredReadTargetCount",
          "bestStructuredReadTarget",
          "bestStructuredReadTargetCount",
          "topReadTarget",
          "topReadTargetCount",
          "citationCount",
          "topCitationId",
          "topCitationPath",
          "topCitationKind",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "searchDecisionRecommendedSourceType",
          "searchDecisionRecommendedSourceHints",
          "searchDecisionFirstOfficialRank",
          "searchDecisionFirstOfficialSourceType",
          "searchDecisionFirstOfficialSourceHints",
          "searchDecisionFirstOfficialDateIso",
          "searchDecisionFirstOfficialDateUnixMs",
          "searchDecisionFirstOfficialCommandArgs",
          "searchDecisionCommand",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "pageDecisionCommand",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopHeadingSelector",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopLandmarkSelector",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopNamedRoleSelector",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopInteractiveControlsTargetRole",
          "semanticTopInteractiveControlsTargetName",
          "semanticTopInteractiveControlsTargetSelector",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopFocusableControlsTargetRole",
          "semanticTopFocusableControlsTargetName",
          "semanticTopFocusableControlsTargetSelector",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "semanticTopButtonControlsTargetRole",
          "semanticTopButtonControlsTargetName",
          "semanticTopButtonControlsTargetSelector",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSecondHeaderPath",
          "semanticTopTableSecondHeaderRole",
          "semanticTopTableSecondHeaderColumnIndex",
          "semanticTopTableSecondHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopTableSecondSampleCellText",
          "semanticTopTableSecondSampleCellPath",
          "semanticTopTableSecondSampleCellRowIndex",
          "semanticTopTableSecondSampleCellColumnIndex",
          "semanticTopTableSecondSampleCellSelector",
          "semanticTopTableSecondSampleCellOwnedTarget",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldLabelledBySelector",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldDescribedBySelector",
          "semanticTopFieldState",
          "semanticTopFieldDetailsSelector",
          "semanticTopFieldErrorMessageSelector",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldControlsTargetRole",
          "semanticTopFieldControlsTargetName",
          "semanticTopFieldControlsTargetSelector",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopSelectedChoiceControlsTargetRole",
          "semanticTopSelectedChoiceControlsTargetName",
          "semanticTopSelectedChoiceControlsTargetSelector",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateControlsTargetRole",
          "semanticTopStateControlsTargetName",
          "semanticTopStateControlsTargetSelector",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "runbookDecision",
          "runbookMode",
          "runbookOperation",
          "runbookReason",
          "runbookExpectedOutcome",
          "pageTitle",
          "pageCanonicalUrl",
          "pageDir",
          "pagePublishedTime",
          "nextActionName",
          "nextExecution",
          "nextCommandArgs",
          "nextReadFrom",
          "expectedOutcomeKind",
          "expectedOutcomeMessage",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanReason",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "topActionName",
          "topActionExecution",
          "topActionCommandArgs",
          "signalCount",
          "signalWarningCount",
          "signalErrorCount",
          "qualityGateCount",
          "qualityGateFailCount",
          "topSignalKind",
          "topSignalMessage",
          "topQualityGateKind",
          "topQualityGatePass",
          "topQualityGateScore",
          "problemSignalKind",
          "problemSignalMessage",
          "failingQualityGateKind",
          "failingQualityGateSeverity",
          "failingQualityGateMessage",
          "failingQualityGateScore",
          "topDiagnosticCode",
          "topDiagnosticSeverity",
          "topDiagnosticMessage",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionSource",
          "alternativeActionExecution",
          "alternativeActionCommandArgs",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "formCount",
          "formChoiceCount",
          "formChoices",
          "actionTargetCount",
          "actionTargetChoiceCount",
          "actionTargetChoices",
          "formChoiceFirstFieldLabel",
          "formChoiceFirstFieldPlaceholder",
          "formChoiceFirstFieldAutocomplete",
          "formChoiceFirstFieldPattern",
          "formChoiceFirstFieldRequired",
          "formChoiceFirstFieldInvalid",
          "formChoiceSubmitFormActionUrl",
          "formChoiceSubmitFormMethod",
          "actionTargetChoiceName",
          "actionTargetChoiceKind",
          "actionTargetChoiceSource",
          "actionTargetChoiceRank",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchFindQueryCount",
          "sourceSearchTopFindQuery",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchAlternateCount",
          "hiddenSignalCount",
          "hiddenReadTargetCount",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "sourceLinkCount",
          "sourceChoiceCount",
          "topChoiceKind",
          "topChoicePath",
          "topChoiceCommandArgs",
          "topChoiceUrlPath",
          "topChoiceUrlQuery",
          "topActionTargetUrlPath",
          "topActionTargetUrlQuery",
          "topChoiceRequiredFieldName",
          "topChoiceInvalidFieldInvalid",
          "keeps generic top choice and recommended command in agent brief output",
          "recommendedCommandArgs",
          "citationCount",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "searchDecisionRecommendedSourceType",
          "searchDecisionRecommendedSourceHints",
          "searchDecisionFirstOfficialRank",
          "searchDecisionFirstOfficialSourceType",
          "searchDecisionFirstOfficialSourceHints",
          "searchDecisionFirstOfficialDateIso",
          "searchDecisionFirstOfficialDateUnixMs",
          "searchDecisionFirstOfficialCommandArgs",
          "searchDecisionCommand",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "pageDecisionCommand",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopHeadingSelector",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopLandmarkSelector",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopNamedRoleSelector",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "semanticTopButtonControlsTargetRole",
          "semanticTopButtonControlsTargetName",
          "semanticTopButtonControlsTargetSelector",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSecondHeaderPath",
          "semanticTopTableSecondHeaderRole",
          "semanticTopTableSecondHeaderColumnIndex",
          "semanticTopTableSecondHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopTableSecondSampleCellText",
          "semanticTopTableSecondSampleCellPath",
          "semanticTopTableSecondSampleCellRowIndex",
          "semanticTopTableSecondSampleCellColumnIndex",
          "semanticTopTableSecondSampleCellSelector",
          "semanticTopTableSecondSampleCellOwnedTarget",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldLabelledBySelector",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldDescribedBySelector",
          "semanticTopFieldDetailsSelector",
          "semanticTopFieldErrorMessageSelector",
          "semanticTopFieldState",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldControlsTargetRole",
          "semanticTopFieldControlsTargetName",
          "semanticTopFieldControlsTargetSelector",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopSelectedChoiceControlsTargetRole",
          "semanticTopSelectedChoiceControlsTargetName",
          "semanticTopSelectedChoiceControlsTargetSelector",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateControlsTargetRole",
          "semanticTopStateControlsTargetName",
          "semanticTopStateControlsTargetSelector",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "runbookDecision",
          "runbookMode",
          "runbookOperation",
          "runbookExpectedOutcome",
          "expectedOutcomeKind",
          "expectedOutcomeMessage",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "signalCount",
          "signalWarnings",
          "signalErrors",
          "qualityGateCount",
          "qualityGateFailures",
          "problemSignal",
          "failingQualityGate",
          "failingQualityGateSeverity",
          "failingQualityGateScore",
          "topDiagnostic",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionExecution",
          "alternativeActionCommandArgs",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "brief-generic-choice-routing",
      "Brief agent output must keep generic topChoice routing shortcuts for result, source, form, and action-target choices.",
      "Focused CLI tests prove compact executor output can route without parsing nested choice arrays first.",
      (failures) => {
        requireFileIncludes(root, failures, "src/cli.ts", [
          "function compactAgentTopChoice",
          "topChoiceKind: agent.topChoiceKind",
          "topChoiceCommandArgs",
          "topChoiceSelector",
          "topChoiceUrlPath",
          "topChoiceUrlQuery",
          "topActionTargetUrlPath",
          "topActionTargetUrlQuery",
          "topChoiceRequiredFieldName",
          "topChoiceInvalidFieldInvalid",
          "function compactAgentRecommended",
          "recommendedCommandArgs",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "keeps generic top choice and recommended command in agent brief output",
          "https://www.npmjs.com/package/ax-grep?activeTab=readme",
          "exposes likely official source choice hints without requiring nested source choices",
          "keeps executable form details in brief read handoff",
          "keeps executable action target details in brief read handoff",
          "topFormChoiceFirstFieldLabel",
          "topFormChoiceFirstFieldPlaceholder",
          "topActionTargetChoiceName",
          "topActionTargetUrlPath",
          "topActionTargetUrlQuery",
          "topActionTargetChoiceUrlTemplatePath",
          "topActionTargetChoiceUrlTemplateQuery",
          "topActionTargetChoiceEncodingType",
          "Archive search",
          "Search reports",
          "Docs OpenSearch",
          "topChoiceKind: \"result\"",
          "topChoiceKind: \"source\"",
          "topChoiceKind: \"form\"",
          "topChoiceKind: \"action-target\"",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "semantic-state-text-parity",
      "Text-mode agent output must preserve shallow accessibility state scalars that are already present in JSON/brief output.",
      "formatAgentText prints browser-tree state scalars and a focused CLI test guards the text handoff.",
      (failures) => {
        requireFileIncludes(root, failures, "src/cli.ts", [
          "semanticTopStateHidden",
          " hidden=${agent.semanticTopStateHidden}",
          " disabled=${agent.semanticTopStateDisabled}",
          " checked=${agent.semanticTopStateChecked}",
          " selected=${agent.semanticTopStateSelected}",
          " current=${agent.semanticTopStateCurrent}",
          " focused=${agent.semanticTopStateFocused}",
          " required=${agent.semanticTopStateRequired}",
          " invalid=${agent.semanticTopStateInvalid}",
          " readonly=${agent.semanticTopStateReadonly}",
          "typeof agent.semanticTopInteractiveHaspopup !== \"undefined\"",
          "typeof agent.semanticTopFocusableHaspopup !== \"undefined\"",
          "typeof agent.semanticTopButtonHaspopup !== \"undefined\"",
          "typeof agent.semanticTopFieldInvalid !== \"undefined\"",
          "typeof agent.semanticTopFieldHaspopup !== \"undefined\"",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "prints top accessibility state scalars in text output",
          "semanticTopState: agent.semanticSummary.stateItems[0] role=searchbox name=\\\"Archive search\\\"",
          "disabled=true",
          "required=true",
          "readonly=true",
          "invalid=spelling",
        ]);
        requireFileIncludes(root, failures, "docs/progress.md", [
          "A80",
          "Top accessibility state text parity",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "browser-fallback-command-text",
      "Text-mode and brief browser fallback output must keep copy-ready browser, executor, and handoff command strings beside command args.",
      "Focused CLI tests guard browserHtmlCommand, executorCommand, handoffCommand, and compact nested browser fallback command lines.",
      (failures) => {
        requireFileIncludes(root, failures, "src/cli.ts", [
          "function compactAgentBriefHandoff",
          "handoff.command ? { command: handoff.command }",
          "function compactAgentBrowserHtml",
          "browserHtml.reason ? { reason: browserHtml.reason }",
          "browserHtml.command ? { command: browserHtml.command }",
        ]);
        requireFileIncludes(root, failures, "src/types.ts", [
          "export type AgentBrowserHtmlCapture",
          "reason?: string",
        ]);
        requireFileIncludes(root, failures, "scripts/compare-static.ts", [
          "type CliAgentBrowserHtmlShape",
          "reason?: string",
          "&& (!right.reason || left.reason === right.reason)",
          "&& (!right.command || left.command === right.command)",
          "JSON.stringify(left.commandArgs) === JSON.stringify(right.commandArgs)",
          "executor.command === handoff.command",
          "executor.afterInteractionCommand === handoff.afterInteractionCommand",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "returns a structured warning when the page has no inspectable content",
          "prints browser capture handoff details in text output",
          "keeps brief mode in HTTP error recovery commands",
          "browserHtmlCommand: ax-grep 'https://example.test' --html-file captured.html --json --summary",
          "executorCommand: ax-grep 'https://example.test' --html-file captured.html --json --summary",
          "handoffCommand: ax-grep 'https://example.test' --html-file captured.html --json --summary",
          "reason: \"Fetch failed before a usable page summary was available; retry with browser-captured HTML.\"",
          "command: \"ax-grep 'https://blocked.example/package' --html-file captured.html --find 'target claim' --agent-brief\"",
          "browserHtmlCommandArgs",
          "executorCommandArgs",
          "handoffCommandArgs",
        ]);
        requireFileIncludes(root, failures, "tests/public-types.test.ts", [
          "browserHtml: {",
          "reason: \"Browser-captured HTML is needed.\"",
          "expect(handoff.browserHtml?.reason).toContain(\"Browser-captured HTML\")",
          "expect(handoff.browserHtml?.command).toContain(\"--html-file captured.html\")",
          "expect(envelopeRecommendation.pageCheck.sourceLinks?.[0]?.command).toContain(\"source.example/report\")",
        ]);
        requireFileIncludes(root, failures, "docs/progress.md", [
          "A129",
          "Browser fallback command text coverage",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "public-type-shortcuts",
      "Public TypeScript consumers must see the same action references and count shortcuts as the CLI JSON output.",
      "Public type tests compile the count shortcut and source-link reference surface.",
      (failures) => {
        requireFileIncludes(root, failures, "tests/public-types.test.ts", [
          "AgentSummary",
          "AgentHandoff",
          "sourceLinkRef",
          "AgentFormChoice",
          "AgentActionTargetChoice",
          "resultChoiceCount",
          "formChoiceCount",
          "actionTargetChoiceCount",
          "topFormChoicePath",
          "topFormChoiceUrlTemplate",
          "topFormChoiceSubmitText",
          "topFormChoiceFirstFieldName",
          "topFormChoiceFirstFieldType",
          "topFormChoiceFirstFieldLabel",
          "topFormChoiceFirstFieldPlaceholder",
          "topFormChoiceFirstFieldInvalid",
          "topFormChoiceFirstFieldSelector",
          "topFormChoiceRequiredFieldName",
          "topFormChoiceRequiredFieldType",
          "topFormChoiceRequiredFieldLabel",
          "topFormChoiceRequiredFieldRequired",
          "topFormChoiceRequiredFieldSelector",
          "topFormChoiceInvalidFieldName",
          "topFormChoiceInvalidFieldInvalid",
          "topFormChoiceInvalidFieldSelector",
          "topActionTargetChoicePath",
          "topActionTargetChoiceName",
          "topActionTargetChoiceKind",
          "topActionTargetChoiceSource",
          "topActionTargetChoiceUrlTemplate",
          "topActionTargetChoiceUrlTemplatePath",
          "topActionTargetChoiceUrlTemplateQuery",
          "sourceChoiceCount",
          "topSourceChoicePath",
          "topSourceChoiceUrl",
          "topSourceChoiceHost",
          "topSourceChoiceUrlPath",
          "topSourceChoiceCommandArgs",
          "topSourceChoiceSourceType",
          "topSourceChoiceSourceHints",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "dataTableCount",
          "faqCount",
          "codeBlockCount",
          "resourceCount",
          "mediaCount",
          "sectionCount",
          "breadcrumbCount",
          "paginationCount",
          "tocCount",
          "embedCount",
          "transcriptCount",
          "authorLinkCount",
          "provenanceCount",
          "offerCount",
          "datasetCount",
          "identityCount",
          "timelineCount",
          "contactPointCount",
          "topDataTablePath",
          "topDataTableHeaders",
          "topDataTableSecondRow",
          "topDataTableSecondCell",
          "topFaqQuestion",
          "topResourceUrl",
          "topResourceCommandArgs",
          "topMediaUrl",
          "topMediaCommandArgs",
          "topSectionPath",
          "topSectionHeading",
          "topBreadcrumbText",
          "topPaginationPath",
          "topPaginationUrl",
          "topPaginationCommandArgs",
          "topTocPath",
          "topTocText",
          "topTocFirstItemCommandArgs",
          "topEmbedUrl",
          "topEmbedCommandArgs",
          "topTranscriptUrl",
          "topTranscriptCommandArgs",
          "topAuthorLinkUrl",
          "topAuthorLinkCommandArgs",
          "topProvenancePath",
          "topProvenanceValue",
          "topProvenanceCommandArgs",
          "topOfferPath",
          "topOfferPrice",
          "topOfferPriceAmount",
          "topOfferCommandArgs",
          "topDatasetPath",
          "topDatasetCommandArgs",
          "topDatasetDistributionCommandArgs",
          "topDatasetLicenseUrl",
          "topDatasetLicenseCommandArgs",
          "topDatasetTemporalCoverage",
          "topDatasetSpatialCoverage",
          "topDatasetCreator",
          "topIdentityPath",
          "topIdentityName",
          "topIdentityCommandArgs",
          "topIdentitySameAsCommandArgs",
          "topTimelinePath",
          "topTimelineValue",
          "topTimelineIsoDate",
          "topTimelineUnixMs",
          "topContactPointPath",
          "topContactPointValue",
          "structuredReadTargetCount",
          "bestStructuredReadTarget",
          "bestStructuredReadTargetCount",
          "topHiddenSignalPath",
          "citationCount",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "searchDecisionRecommendedSourceType",
          "searchDecisionRecommendedSourceHints",
          "searchDecisionFirstOfficialRank",
          "searchDecisionFirstOfficialSourceType",
          "searchDecisionFirstOfficialSourceHints",
          "searchDecisionFirstOfficialDateIso",
          "searchDecisionFirstOfficialDateUnixMs",
          "searchDecisionFirstOfficialCommandArgs",
          "searchDecisionCommand",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "pageDecisionCommand",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopInteractiveControlsTargetRole",
          "semanticTopInteractiveControlsTargetName",
          "semanticTopInteractiveControlsTargetSelector",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopFocusableControlsTargetRole",
          "semanticTopFocusableControlsTargetName",
          "semanticTopFocusableControlsTargetSelector",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "semanticTopButtonControlsTargetRole",
          "semanticTopButtonControlsTargetName",
          "semanticTopButtonControlsTargetSelector",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSecondHeaderPath",
          "semanticTopTableSecondHeaderRole",
          "semanticTopTableSecondHeaderColumnIndex",
          "semanticTopTableSecondHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopTableSecondSampleCellText",
          "semanticTopTableSecondSampleCellPath",
          "semanticTopTableSecondSampleCellRowIndex",
          "semanticTopTableSecondSampleCellColumnIndex",
          "semanticTopTableSecondSampleCellSelector",
          "semanticTopTableSecondSampleCellOwnedTarget",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldState",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldControlsTargetRole",
          "semanticTopFieldControlsTargetName",
          "semanticTopFieldControlsTargetSelector",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopSelectedChoiceControlsTargetRole",
          "semanticTopSelectedChoiceControlsTargetName",
          "semanticTopSelectedChoiceControlsTargetSelector",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "runbookDecision",
          "runbookOperation",
          "runbookExpectedOutcome",
          "pageTitle",
          "pageCanonicalUrl",
          "pageDir",
          "pagePublishedTime",
          "nextActionName",
          "nextExecution",
          "nextCommandArgs",
          "nextReadFrom",
          "expectedOutcomeKind",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "signalCount",
          "signalWarningCount",
          "signalErrorCount",
          "qualityGateCount",
          "qualityGateFailCount",
          "topSignalKind",
          "topQualityGateKind",
          "topQualityGatePass",
          "problemSignalKind",
          "problemSignalMessage",
          "failingQualityGateKind",
          "failingQualityGateSeverity",
          "failingQualityGateMessage",
          "failingQualityGateScore",
          "topDiagnosticCode",
          "topDiagnosticSeverity",
          "topDiagnosticMessage",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionExecution",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchAlternateCount",
          "hiddenSignalCount",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "actionTargetCount",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "readme-doc-split",
      "README must stay concise; long operational and agent details belong under docs/.",
      "README line limits and docs index links are enforced by tests and readiness audit.",
      (failures) => {
        checkReadmeSplit(root, failures);
        requireFileIncludes(root, failures, "tests/readme.test.ts", [
          "stays concise",
          "docs",
          "README.md",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "progress-tracker-current",
      "Progress tracking must stay detailed enough to resume the long-running research without bloating README.",
      "docs/progress.md records estimates, expansion rules, active work, and recent A80+ handoff evidence.",
      (failures) => {
        requireFileIncludes(root, failures, "docs/progress.md", [
          "Status: about",
          "This is a research track",
          "Current forecast board",
          "Near-term queue with prediction",
          "Active Work Tracker",
          "Remaining Work Breakdown",
          "Research Scope Ledger",
          "A80",
          "A81",
          "A82",
          "A83",
          "A84",
          "A85",
          "A86",
          "A87",
          "A88",
          "A89",
          "A90",
          "A91",
          "A92",
          "A93",
          "A94",
          "A95",
          "A96",
          "A97",
          "A98",
          "A99",
          "A100",
          "A101",
          "A102",
          "A103",
          "A104",
          "A105",
          "A106",
          "A107",
          "A108",
          "A109",
          "A110",
          "A111",
          "A112",
          "A113",
          "A114",
          "A115",
          "A116",
          "A117",
          "A118",
          "A119",
          "A120",
          "A121",
          "A122",
          "A123",
          "A124",
          "A125",
          "A126",
          "A127",
          "A128",
          "A129",
          "A130",
          "A131",
          "A132",
          "A133",
          "A134",
          "A135",
          "A136",
          "A137",
          "A138",
          "A139",
          "A140",
          "A141",
          "A142",
        ]);
      },
    ),
  ];
}

if (isMainModule()) {
  const failures = checkAgentReadinessProject();
  if (failures.length > 0) {
    for (const failure of failures) {
      console.error(`${failure.file}: ${failure.message}`);
    }
    process.exit(1);
  }
  console.log(`agent-readiness: audit ok (${collectAgentReadinessEvidence().length} evidence checks)`);
}

function evidenceCheck(
  root: string,
  id: string,
  requirement: string,
  evidence: string,
  inspect: (failures: ReadinessFailure[]) => void,
): ReadinessEvidence {
  const failures: ReadinessFailure[] = [];
  inspect(failures);
  return {
    id,
    requirement,
    evidence,
    status: failures.length === 0 ? "pass" : "fail",
    failures,
  };
}

function readJson<T>(root: string, relativePath: string, failures: ReadinessFailure[]): T | undefined {
  const file = join(root, relativePath);
  if (!existsSync(file)) {
    failures.push({ file: relativePath, message: "missing file" });
    return undefined;
  }

  try {
    return JSON.parse(readFileSync(file, "utf8")) as T;
  } catch (error) {
    failures.push({ file: relativePath, message: `invalid JSON: ${String(error)}` });
    return undefined;
  }
}

function readText(root: string, relativePath: string, failures: ReadinessFailure[]): string | undefined {
  const file = join(root, relativePath);
  if (!existsSync(file)) {
    failures.push({ file: relativePath, message: "missing file" });
    return undefined;
  }
  return readFileSync(file, "utf8");
}

function requireScript(
  failures: ReadinessFailure[],
  scripts: Record<string, string>,
  name: string,
  expectedText: string,
): void {
  const value = scripts[name];
  if (typeof value === "string" && value.includes(expectedText)) return;
  failures.push({
    file: "package.json",
    message: `script ${name} must include ${JSON.stringify(expectedText)}`,
  });
}

function requireFileIncludes(
  root: string,
  failures: ReadinessFailure[],
  relativePath: string,
  requiredTexts: string[],
): void {
  const text = readText(root, relativePath, failures);
  if (typeof text !== "string") return;

  for (const requiredText of requiredTexts) {
    if (text.includes(requiredText)) continue;
    failures.push({
      file: relativePath,
      message: `missing required text ${JSON.stringify(requiredText)}`,
    });
  }
}

function checkReadmeSplit(root: string, failures: ReadinessFailure[]): void {
  const readme = readText(root, "README.md", failures);
  if (typeof readme !== "string") return;

  const lineCount = readme.trimEnd().split(/\r?\n/).length;
  if (lineCount > 80) {
    failures.push({ file: "README.md", message: `README must stay concise, got ${lineCount} lines` });
  }
  if (!readme.includes("./docs/README.md")) {
    failures.push({ file: "README.md", message: "README must link to docs/README.md" });
  }

  requireFileIncludes(root, failures, "docs/README.md", [
    "./cli-agent.md",
    "./agent-handoff.md",
    "./agent-readiness.md",
    "./benchmarks.md",
    "./comparison-baseline.md",
  ]);
}

function isMainModule(): boolean {
  const entrypoint = process.argv[1];
  if (!entrypoint) return false;
  return import.meta.url === pathToFileURL(entrypoint).href;
}
