import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

type ReadinessFailure = {
  file: string;
  message: string;
};

export type ReadinessEvidence = {
  id: string;
  requirement: string;
  evidence: string;
  status: "pass" | "fail";
  failures: ReadinessFailure[];
};

type PackageJson = {
  scripts?: Record<string, string>;
};

export function checkAgentReadinessProject(root = process.cwd()): ReadinessFailure[] {
  const failures: ReadinessFailure[] = [];
  const packageJson = readJson<PackageJson>(root, "package.json", failures);
  const scripts = packageJson?.scripts ?? {};

  requireScript(failures, scripts, "check", "tsc --noEmit");
  requireScript(failures, scripts, "compare:gate", "scripts/check-comparison-gates.ts");
  requireScript(failures, scripts, "compare:static:fixtures:gate", "scripts/check-fixture-static-gate.ts");
  requireScript(failures, scripts, "check:processes", "scripts/check-project-processes.ts");
  requireScript(failures, scripts, "readiness:audit", "scripts/check-agent-readiness.ts");
  requireScript(failures, scripts, "readiness:real-page-smoke", "scripts/check-real-page-smoke.ts");
  requireScript(failures, scripts, "readiness:agent-browser-smoke", "scripts/check-agent-browser-smoke.ts");

  requireFileIncludes(root, failures, "vitest.config.ts", [
    "fileParallelism: false",
    "maxWorkers: 1",
  ]);
  requireFileIncludes(root, failures, "AGENTS.md", [
    "Do not run project tests, comparison scripts, or browser-backed checks in\n  parallel",
    "After any browser-backed command, verify that no project-owned browser or\n  `agent-browser` process was left behind",
  ]);
  requireFileIncludes(root, failures, "docs/benchmarks.md", [
    "pnpm compare:static:fixtures:gate",
    "pnpm check:processes",
    "uses synthetic\nHTML fixtures only",
  ]);
  requireFileIncludes(root, failures, "docs/comparison-baseline.md", [
    "Operational rule: run comparison suites sequentially",
    "averageCliAgentScore",
    "minCliAgentScore",
    "weakAgentTargets",
    "averageAgentExecutorScore",
    "minAgentExecutorScore",
    "averageAgentTopReadTargetShortcutScore",
    "averageAgentFormActionCountScore",
    "averageAgentChoiceCountScore",
    "averageAgentTopChoiceShortcutScore",
    "averageAgentTopResultChoiceShortcutScore",
    "averageAgentTopCitationShortcutScore",
    "averageAgentEvidenceCountShortcutScore",
    "averageAgentSignalCountShortcutScore",
    "averageAgentTopQualityShortcutScore",
    "averageAgentProblemShortcutScore",
    "averageAgentExecutorShortcutScore",
    "averageAgentHandoffShortcutScore",
    "averageAgentAnswerShortcutScore",
    "averageAgentTopActionShortcutScore",
    "averageAgentFormActionChoiceScore",
    "averageAgentVerificationQueryScore",
    "averageAgentSourceSearchShortcutScore",
    "averageAgentHiddenSignalScore",
    "averageAgentHiddenSignalCountScore",
    "averageAgentTopHiddenSignalShortcutScore",
    "averageAgentPageMetadataShortcutScore",
  ]);
  requireFileIncludes(root, failures, "docs/agent-readiness.md", [
    "Do not call this objective complete from unit tests alone",
    "Browser-backed comparison suites must run sequentially",
    "process cleanup before and after browser-backed comparison commands",
  ]);
  requireFileIncludes(root, failures, "scripts/check-fixture-static-gate.ts", [
    "agent-fixtures",
    "runStaticComparisons",
    "checkComparisonGateReport",
  ]);
  requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
    "agent-fixtures",
    "!warning.includes(\"agent-browser\")",
    "checkComparisonGateReport(report)",
  ]);
  requireFileIncludes(root, failures, "tests/process-check.test.ts", [
    "findProjectProcesses",
    "agent-browser",
    "pnpm compare:static:fixtures:gate",
  ]);

  checkReadmeSplit(root, failures);
  for (const evidence of collectAgentReadinessEvidence(root)) {
    if (evidence.status === "pass") continue;
    for (const failure of evidence.failures) {
      failures.push({
        file: failure.file,
        message: `[${evidence.id}] ${failure.message}`,
      });
    }
  }

  return failures;
}

export function collectAgentReadinessEvidence(root = process.cwd()): ReadinessEvidence[] {
  return [
    evidenceCheck(
      root,
      "resource-safety",
      "Project validation must run with concurrency 1 and leave no project browser/test processes behind.",
      "AGENTS.md, vitest.config.ts, docs, and pnpm check:processes encode the operational safety rule.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "check:processes", "scripts/check-project-processes.ts");
        requireFileIncludes(root, failures, "vitest.config.ts", ["fileParallelism: false", "maxWorkers: 1"]);
        requireFileIncludes(root, failures, "AGENTS.md", [
          "Do not run project tests, comparison scripts, or browser-backed checks in\n  parallel",
          "After any browser-backed command, verify that no project-owned browser or\n  `agent-browser` process was left behind",
        ]);
        requireFileIncludes(root, failures, "docs/benchmarks.md", ["pnpm check:processes"]);
      },
    ),
    evidenceCheck(
      root,
      "fixture-loop-coverage",
      "Search and page-check agent loops must be covered without starting browsers or remote fetches.",
      "The fixture gate uses synthetic HTML targets for search open/refine, site search, hidden metadata, actions, and browser HTML retry.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/benchmark-targets.ts", [
          "Synthetic search open gate",
          "Synthetic search refine gate",
          "Synthetic site search recovery gate",
          "Synthetic hidden metadata gate",
          "Synthetic action target gate",
          "Synthetic browser HTML retry gate",
        ]);
        requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
          "open-result",
          "refine-search",
          "open-site-search",
          "retry-with-browser-html",
          "!warning.includes(\"agent-browser\")",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "real-page-smoke",
      "At least one real page must prove static agent handoff without `agent-browser` before claiming browser parity progress.",
      "readiness:real-page-smoke checks https://example.com with --agent-brief, no Puppeteer, and no agent-browser process.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:real-page-smoke", "scripts/check-real-page-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-real-page-smoke.ts", [
          "https://example.com",
          "--agent-brief",
          "needsBrowserHtml",
          "canUseFetchedHtml",
          "semanticNamedRoleCount",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "agent-browser-smoke",
      "At least one bounded `agent-browser` comparison must prove static named-role parity before the goal can move beyond local and fetched-page smoke evidence.",
      "readiness:agent-browser-smoke runs pnpm compare on https://example.com, https://books.toscrape.com/, https://news.ycombinator.com, and https://www.gov.uk/foreign-travel-advice with per-target floors.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:agent-browser-smoke", "scripts/check-agent-browser-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-agent-browser-smoke.ts", [
          "https://example.com",
          "https://books.toscrape.com/",
          "https://news.ycombinator.com",
          "https://www.gov.uk/foreign-travel-advice",
          "pnpm",
          "compare",
          "agentBrowser",
          "overlap",
          "agentReadiness",
          "minReadinessScore",
        ]);
        requireFileIncludes(root, failures, "scripts/check-project-processes.ts", [
          "scripts\\/compare\\.ts",
          "pnpm\\s+compare",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "agent-browser-text-heavy-smoke",
      "Text-heavy document pages must not be judged only by raw StaticText volume when action, navigation, and structural content parity are usable.",
      "readiness:agent-browser-text-heavy-smoke runs pnpm compare on Korean Wikipedia and enforces structuralContentRecall and textRecall reporting separately.",
      (failures) => {
        const packageJson = readJson<PackageJson>(root, "package.json", failures);
        requireScript(failures, packageJson?.scripts ?? {}, "readiness:agent-browser-text-heavy-smoke", "scripts/check-agent-browser-text-heavy-smoke.ts");
        requireFileIncludes(root, failures, "scripts/check-agent-browser-text-heavy-smoke.ts", [
          "https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD",
          "pnpm",
          "compare",
          "structuralContentRecall",
          "textRecall",
          "agentReadiness",
          "agentBrowser",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "per-target-gates",
      "No included target may hide behind good averages when agent output is too weak.",
      "Static comparison gates enforce per-target CLI and executor floors in addition to average scores.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/check-comparison-gates.ts", [
          "minCliAgentScore",
          "minAgentExecutorScore",
          "averageCliAgentScore",
          "averageAgentExecutorScore",
          "averageAgentTopReadTargetShortcutScore",
          "averageAgentFormActionChoiceScore",
          "averageAgentChoiceCountScore",
          "averageAgentTopChoiceShortcutScore",
          "averageAgentTopResultChoiceShortcutScore",
          "averageAgentTopCitationShortcutScore",
          "averageAgentEvidenceCountShortcutScore",
          "averageAgentSignalCountShortcutScore",
          "averageAgentProblemShortcutScore",
          "averageAgentExecutorShortcutScore",
          "averageAgentHandoffShortcutScore",
          "averageAgentAnswerShortcutScore",
          "averageAgentTopActionShortcutScore",
          "averageAgentVerificationQueryScore",
          "averageAgentSourceSearchShortcutScore",
          "averageAgentTopReadTargetShortcutScore",
          "averageAgentTopActionShortcutScore",
        ]);
        requireFileIncludes(root, failures, "scripts/compare-static.ts", [
          "sourceSearchSelectedCommandArgs",
          "sourceSearchAlternateCommandArgs",
        ]);
        requireFileIncludes(root, failures, "docs/comparison-baseline.md", [
          "minCliAgentScore",
          "minAgentExecutorScore",
          "averageAgentFormActionChoiceScore",
          "averageAgentChoiceCountScore",
          "averageAgentTopChoiceShortcutScore",
          "averageAgentTopCitationShortcutScore",
          "averageAgentEvidenceCountShortcutScore",
          "averageAgentSignalCountShortcutScore",
          "averageAgentProblemShortcutScore",
          "averageAgentExecutorShortcutScore",
          "averageAgentHandoffShortcutScore",
          "averageAgentAnswerShortcutScore",
          "averageAgentVerificationQueryScore",
          "averageAgentSourceSearchShortcutScore",
          "sourceSearchSelectedCommandArgs",
          "sourceSearchAlternateCommandArgs",
          "agent.handoff",
          "agent.executor",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "weak-target-diagnostics",
      "When a target fails the floor, the report must name the weak target and its agent status/action.",
      "compare:gate emits weakAgentTargets with category, URL, scores, status, and primary action.",
      (failures) => {
        requireFileIncludes(root, failures, "scripts/check-comparison-gates.ts", [
          "weakAgentTargets",
          "weakAgentTarget",
          "primaryAction",
          "agentStatus",
        ]);
        requireFileIncludes(root, failures, "tests/comparison-gate.test.ts", [
          "weakAgentTarget",
          "minCliAgentScore",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "executable-agent-continuations",
      "Subagents must receive executable next commands for search, source, form, action-target, and browser-retry loops.",
      "CLI tests and fixture gates cover commandArgs/result/source choices, page actions, and browser HTML retry actions.",
      (failures) => {
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "resultChoices",
          "topResultChoicePath",
          "topResultChoiceHost",
          "topResultChoiceCommandArgs",
          "topResultChoiceSourceType",
          "topResultChoiceSourceScore",
          "topResultChoiceSourceHints",
          "topResultChoiceDateText",
          "topResultChoiceRelevance",
          "topResultChoiceMatchedTerm",
          "topResultChoiceFindMatch",
          "topResultChoiceLikelyOfficial",
          "topResultChoiceSitelinkCount",
          "topResultChoiceFirstSitelinkTitle",
          "topResultChoiceFirstSitelinkUrl",
          "commandArgs",
          "sourceLinkRef",
          "formChoices",
          "actionTargetChoices",
          "executor",
          "handoff",
          "forms",
          "actionTargets",
        ]);
        requireFileIncludes(root, failures, "tests/compare-static-fixture.test.ts", [
          "agentPrimaryAction",
          "retry-with-browser-html",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "count-shortcuts",
      "Agent output must expose quick count shortcuts so subagents can judge page richness without parsing nested arrays.",
      "Agent summaries and text output expose result, evidence, form/action, hidden-signal, read-target, and source-link counts.",
      (failures) => {
        requireFileIncludes(root, failures, "src/types.ts", [
          "resultCount",
          "resultChoiceCount",
          "formCount",
          "formChoiceCount",
          "formChoices",
          "topFormChoicePath",
          "topFormChoiceUrlTemplate",
          "topFormChoiceQueryField",
          "topFormChoiceSubmitText",
          "topFormChoiceFirstFieldName",
          "topFormChoiceFirstFieldType",
          "topFormChoiceFirstFieldSelector",
          "actionTargetCount",
          "actionTargetChoiceCount",
          "actionTargetChoices",
          "topActionTargetChoicePath",
          "topActionTargetChoiceUrlTemplate",
          "topActionTargetChoiceQueryInput",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchFindQueryCount",
          "sourceSearchTopFindQuery",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchFailureHost",
          "sourceSearchAlternateCount",
          "sourceSearchAlternateDifferentHost",
          "needsBrowserInteraction",
          "hiddenSignalCount",
          "hiddenReadTargetCount",
          "topHiddenSignalPath",
          "topHiddenSignalText",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "sourceLinkCount",
          "sourceChoiceCount",
          "topSourceChoicePath",
          "topSourceChoiceUrl",
          "topSourceChoiceHost",
          "topSourceChoiceCommandArgs",
          "topSourceChoiceSourceType",
          "topSourceChoiceSourceHints",
          "topChoiceKind",
          "topChoicePath",
          "topChoiceCommandArgs",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "topBarrierText",
          "dataTableCount",
          "faqCount",
          "codeBlockCount",
          "resourceCount",
          "mediaCount",
          "sectionCount",
          "breadcrumbCount",
          "paginationCount",
          "tocCount",
          "embedCount",
          "transcriptCount",
          "authorLinkCount",
          "provenanceCount",
          "offerCount",
          "datasetCount",
          "identityCount",
          "timelineCount",
          "contactPointCount",
          "topDataTablePath",
          "topFaqQuestion",
          "topCodeBlockText",
          "topResourceUrl",
          "topMediaUrl",
          "topSectionPath",
          "topSectionHeading",
          "topSectionLevel",
          "topBreadcrumbText",
          "topPaginationPath",
          "topPaginationUrl",
          "topTocPath",
          "topTocText",
          "topTocFirstItemLabel",
          "topEmbedUrl",
          "topTranscriptUrl",
          "topAuthorLinkUrl",
          "topProvenancePath",
          "topProvenanceValue",
          "topOfferPath",
          "topOfferPrice",
          "topDatasetPath",
          "topDatasetLicenseUrl",
          "topIdentityPath",
          "topIdentityName",
          "topTimelinePath",
          "topTimelineValue",
          "topContactPointPath",
          "topContactPointValue",
          "structuredReadTargetCount",
          "bestStructuredReadTarget",
          "bestStructuredReadTargetCount",
          "topReadTarget",
          "topReadTargetCount",
          "citationCount",
          "topCitationId",
          "topCitationPath",
          "topCitationKind",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldState",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "runbookDecision",
          "runbookMode",
          "runbookOperation",
          "runbookReason",
          "runbookExpectedOutcome",
          "pageTitle",
          "pageCanonicalUrl",
          "pageDir",
          "pagePublishedTime",
          "nextActionName",
          "nextExecution",
          "nextCommandArgs",
          "nextReadFrom",
          "expectedOutcomeKind",
          "expectedOutcomeMessage",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanReason",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "topActionName",
          "topActionExecution",
          "topActionCommandArgs",
          "signalCount",
          "signalWarningCount",
          "signalErrorCount",
          "qualityGateCount",
          "qualityGateFailCount",
          "topSignalKind",
          "topSignalMessage",
          "topQualityGateKind",
          "topQualityGatePass",
          "topQualityGateScore",
          "problemSignalKind",
          "problemSignalMessage",
          "failingQualityGateKind",
          "failingQualityGateSeverity",
          "failingQualityGateMessage",
          "failingQualityGateScore",
          "topDiagnosticCode",
          "topDiagnosticSeverity",
          "topDiagnosticMessage",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionSource",
          "alternativeActionExecution",
          "alternativeActionCommandArgs",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "formCount",
          "formChoiceCount",
          "formChoices",
          "actionTargetCount",
          "actionTargetChoiceCount",
          "actionTargetChoices",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchFindQueryCount",
          "sourceSearchTopFindQuery",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchAlternateCount",
          "hiddenSignalCount",
          "hiddenReadTargetCount",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "sourceLinkCount",
          "sourceChoiceCount",
          "topChoiceKind",
          "topChoicePath",
          "topChoiceCommandArgs",
          "citationCount",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "staticReadiness",
          "staticReadinessReason",
          "staticReadinessReadFrom",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldState",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "runbookDecision",
          "runbookMode",
          "runbookOperation",
          "runbookExpectedOutcome",
          "expectedOutcomeKind",
          "expectedOutcomeMessage",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "signalCount",
          "signalWarnings",
          "signalErrors",
          "qualityGateCount",
          "qualityGateFailures",
          "problemSignal",
          "failingQualityGate",
          "failingQualityGateSeverity",
          "failingQualityGateScore",
          "topDiagnostic",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionExecution",
          "alternativeActionCommandArgs",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "semantic-state-text-parity",
      "Text-mode agent output must preserve shallow accessibility state scalars that are already present in JSON/brief output.",
      "formatAgentText prints browser-tree state scalars and a focused CLI test guards the text handoff.",
      (failures) => {
        requireFileIncludes(root, failures, "src/cli.ts", [
          "semanticTopStateHidden",
          " hidden=${agent.semanticTopStateHidden}",
          " disabled=${agent.semanticTopStateDisabled}",
          " checked=${agent.semanticTopStateChecked}",
          " selected=${agent.semanticTopStateSelected}",
          " current=${agent.semanticTopStateCurrent}",
          " focused=${agent.semanticTopStateFocused}",
          " required=${agent.semanticTopStateRequired}",
          " invalid=${agent.semanticTopStateInvalid}",
          " readonly=${agent.semanticTopStateReadonly}",
          "typeof agent.semanticTopInteractiveHaspopup !== \"undefined\"",
          "typeof agent.semanticTopFocusableHaspopup !== \"undefined\"",
          "typeof agent.semanticTopButtonHaspopup !== \"undefined\"",
          "typeof agent.semanticTopFieldInvalid !== \"undefined\"",
          "typeof agent.semanticTopFieldHaspopup !== \"undefined\"",
        ]);
        requireFileIncludes(root, failures, "tests/cli.test.ts", [
          "prints top accessibility state scalars in text output",
          "semanticTopState: agent.semanticSummary.stateItems[0] searchbox:Archive search",
          "disabled=true",
          "required=true",
          "readonly=true",
          "invalid=spelling",
        ]);
        requireFileIncludes(root, failures, "docs/progress.md", [
          "A80",
          "Top accessibility state text parity",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "public-type-shortcuts",
      "Public TypeScript consumers must see the same action references and count shortcuts as the CLI JSON output.",
      "Public type tests compile the count shortcut and source-link reference surface.",
      (failures) => {
        requireFileIncludes(root, failures, "tests/public-types.test.ts", [
          "AgentSummary",
          "AgentHandoff",
          "sourceLinkRef",
          "AgentFormChoice",
          "AgentActionTargetChoice",
          "resultChoiceCount",
          "formChoiceCount",
          "actionTargetChoiceCount",
          "topFormChoicePath",
          "topFormChoiceUrlTemplate",
          "topFormChoiceSubmitText",
          "topFormChoiceFirstFieldName",
          "topFormChoiceFirstFieldType",
          "topFormChoiceFirstFieldSelector",
          "topActionTargetChoicePath",
          "topActionTargetChoiceUrlTemplate",
          "sourceChoiceCount",
          "topSourceChoicePath",
          "topSourceChoiceUrl",
          "topSourceChoiceHost",
          "topSourceChoiceCommandArgs",
          "topSourceChoiceSourceType",
          "topSourceChoiceSourceHints",
          "barrierCount",
          "topBarrierKind",
          "topBarrierPath",
          "dataTableCount",
          "faqCount",
          "codeBlockCount",
          "resourceCount",
          "mediaCount",
          "sectionCount",
          "breadcrumbCount",
          "paginationCount",
          "tocCount",
          "embedCount",
          "transcriptCount",
          "authorLinkCount",
          "provenanceCount",
          "offerCount",
          "datasetCount",
          "identityCount",
          "timelineCount",
          "contactPointCount",
          "topDataTablePath",
          "topFaqQuestion",
          "topResourceUrl",
          "topMediaUrl",
          "topSectionPath",
          "topSectionHeading",
          "topBreadcrumbText",
          "topPaginationPath",
          "topPaginationUrl",
          "topTocPath",
          "topTocText",
          "topEmbedUrl",
          "topTranscriptUrl",
          "topAuthorLinkUrl",
          "topProvenancePath",
          "topProvenanceValue",
          "topOfferPath",
          "topOfferPrice",
          "topDatasetPath",
          "topDatasetLicenseUrl",
          "topIdentityPath",
          "topIdentityName",
          "topTimelinePath",
          "topTimelineValue",
          "topContactPointPath",
          "topContactPointValue",
          "structuredReadTargetCount",
          "bestStructuredReadTarget",
          "bestStructuredReadTargetCount",
          "topHiddenSignalPath",
          "citationCount",
          "answerEvidenceCount",
          "topAnswerEvidenceId",
          "topAnswerEvidencePath",
          "topAnswerEvidenceKind",
          "topAnswerEvidenceText",
          "searchDecisionName",
          "searchDecisionConfidence",
          "searchDecisionResultCount",
          "pageDecisionName",
          "pageDecisionConfidence",
          "pageDecisionReadFrom",
          "semanticNodeCount",
          "semanticNamedRoleCount",
          "semanticFocusableCount",
          "semanticHeadingCount",
          "semanticLandmarkCount",
          "semanticLinkCount",
          "semanticButtonCount",
          "semanticImageCount",
          "semanticTableCount",
          "semanticListCount",
          "semanticFieldCount",
          "semanticDescriptionCount",
          "semanticValueCount",
          "semanticRelationCount",
          "semanticChoiceCount",
          "semanticStateCount",
          "semanticUnavailableCount",
          "semanticTopRole",
          "semanticOutlineCount",
          "semanticTopOutlinePath",
          "semanticTopOutlineKind",
          "semanticTopOutlineRole",
          "semanticTopOutlineText",
          "semanticTopOutlineDepth",
          "semanticTopOutlineParentPath",
          "semanticTopOutlineParentRole",
          "semanticKeyboardShortcutCount",
          "semanticTopKeyboardShortcutPath",
          "semanticTopKeyboardShortcutRole",
          "semanticTopKeyboardShortcutAccessKey",
          "semanticTopKeyboardShortcutFocusable",
          "semanticTopHeading",
          "semanticTopHeadingPath",
          "semanticTopHeadingLevel",
          "semanticTopLandmark",
          "semanticTopLandmarkPath",
          "semanticTopLandmarkRole",
          "semanticTopNamedRole",
          "semanticTopNamedRolePath",
          "semanticTopNamedRoleRole",
          "semanticTopNamedRoleName",
          "semanticTopNamedRoleDescription",
          "semanticTopInteractiveName",
          "semanticTopInteractivePath",
          "semanticTopInteractiveRoleDescription",
          "semanticTopInteractiveDescription",
          "semanticTopInteractiveValue",
          "semanticTopInteractiveState",
          "semanticTopFocusableRole",
          "semanticTopFocusablePath",
          "semanticTopFocusableName",
          "semanticTopFocusableRoleDescription",
          "semanticTopLinkUrl",
          "semanticTopLinkPath",
          "semanticTopLinkName",
          "semanticTopLinkTarget",
          "semanticTopLinkRel",
          "semanticTopLinkType",
          "semanticTopLinkHreflang",
          "semanticTopLinkState",
          "semanticTopLinkCurrent",
          "semanticTopLinkDownload",
          "semanticInPageLinkCount",
          "semanticTopInPageLinkPath",
          "semanticTopInPageLinkKind",
          "semanticTopInPageLinkTargetId",
          "semanticTopButtonDescription",
          "semanticTopButtonRoleDescription",
          "semanticTopButtonType",
          "semanticTopButtonState",
          "semanticTopButtonDisabled",
          "semanticTopButtonPressed",
          "semanticTopButtonExpanded",
          "semanticTopButtonHaspopup",
          "semanticTopButtonControls",
          "semanticTopButtonFormAction",
          "semanticTopButtonFormMethod",
          "semanticTopButtonFormTarget",
          "semanticTopButtonFormEncType",
          "semanticTopButtonFormNoValidate",
          "semanticTopButtonFormId",
          "semanticTopImagePath",
          "semanticTopImageName",
          "semanticTopImageWidth",
          "semanticTopImageHeight",
          "semanticTopImageLoading",
          "semanticTopImageDecoding",
          "semanticTopImageSrcset",
          "semanticTopImageSizes",
          "semanticTopTableRole",
          "semanticTopTablePath",
          "semanticTopTableRowCount",
          "semanticTopTableColumnCount",
          "semanticTopTableDeclaredRowCount",
          "semanticTopTableDeclaredColumnCount",
          "semanticTopTableHeaders",
          "semanticTopTableHeaderRefs",
          "semanticTopTableFirstHeaderPath",
          "semanticTopTableFirstHeaderRole",
          "semanticTopTableFirstHeaderColumnIndex",
          "semanticTopTableFirstHeaderSort",
          "semanticTopTableSampleCells",
          "semanticTopTableSampleCellRefs",
          "semanticTopSelectedTableCellHeaders",
          "semanticTopSelectedTableCellRowSpan",
          "semanticTopSelectedTableCellColumnSpan",
          "semanticTopSelectedTableCellRowHeaders",
          "semanticTopSelectedTableCellColumnHeaders",
          "semanticTopSelectedTableCellOwnedTarget",
          "semanticTopListRole",
          "semanticTopListPath",
          "semanticTopListItemCount",
          "semanticTopListItems",
          "semanticTopFieldRole",
          "semanticTopFieldPath",
          "semanticTopFieldName",
          "semanticTopFieldHtmlName",
          "semanticTopFieldHtmlType",
          "semanticTopFieldPlaceholder",
          "semanticTopFieldAriaPlaceholder",
          "semanticTopFieldAutocomplete",
          "semanticTopFieldAriaAutocomplete",
          "semanticTopFieldInputMode",
          "semanticTopFieldPattern",
          "semanticTopFieldMin",
          "semanticTopFieldMax",
          "semanticTopFieldStep",
          "semanticTopFieldMinLength",
          "semanticTopFieldMaxLength",
          "semanticTopFieldLabelledBy",
          "semanticTopFieldLabelledByText",
          "semanticTopFieldDescribedBy",
          "semanticTopFieldDescribedByText",
          "semanticTopFieldState",
          "semanticTopFieldDisabled",
          "semanticTopFieldRequired",
          "semanticTopFieldReadonly",
          "semanticTopFieldInvalid",
          "semanticTopFieldChecked",
          "semanticTopFieldExpanded",
          "semanticTopFieldHaspopup",
          "semanticTopFieldControls",
          "semanticTopFieldValueMin",
          "semanticTopFieldValueMax",
          "semanticTopFieldValueNow",
          "semanticTopFieldValueText",
          "semanticTopDescriptionPath",
          "semanticTopDescriptionText",
          "semanticTopValuePath",
          "semanticTopValue",
          "semanticTopRelationPath",
          "semanticTopRelation",
          "semanticTopRelationTarget",
          "semanticTopRelationTargetRole",
          "semanticTopRelationTargetSelector",
          "semanticTopChoiceRole",
          "semanticTopChoicePath",
          "semanticTopChoiceName",
          "semanticTopChoiceState",
          "semanticTopChoiceSelected",
          "semanticTopChoiceCurrent",
          "semanticTopChoiceLevel",
          "semanticTopChoicePosInSet",
          "semanticTopChoiceSetSize",
          "semanticTopStateRole",
          "semanticTopStatePath",
          "semanticTopState",
          "semanticTopStateBusy",
          "semanticTopStateMultiselectable",
          "semanticTopStateSort",
          "semanticTopStateGrabbed",
          "semanticTopStateDropEffect",
          "semanticTopStateCurrent",
          "semanticTopStateControls",
          "semanticTopStateHaspopup",
          "semanticTopStateInvalid",
          "semanticTopStateLive",
          "semanticTopStateOrientation",
          "semanticTopStateValueNow",
          "semanticTopStateValueText",
          "semanticTopUnavailablePath",
          "semanticTopUnavailableReason",
          "semanticTopButtonPath",
          "semanticTopButtonName",
          "runbookDecision",
          "runbookOperation",
          "runbookExpectedOutcome",
          "pageTitle",
          "pageCanonicalUrl",
          "pageDir",
          "pagePublishedTime",
          "nextActionName",
          "nextExecution",
          "nextCommandArgs",
          "nextReadFrom",
          "expectedOutcomeKind",
          "executionPlanOperation",
          "executionPlanConfidence",
          "executionPlanExpectedOutcome",
          "readTargetCount",
          "actionCount",
          "signalCount",
          "signalWarningCount",
          "signalErrorCount",
          "qualityGateCount",
          "qualityGateFailCount",
          "topSignalKind",
          "topQualityGateKind",
          "topQualityGatePass",
          "problemSignalKind",
          "problemSignalMessage",
          "failingQualityGateKind",
          "failingQualityGateSeverity",
          "failingQualityGateMessage",
          "failingQualityGateScore",
          "topDiagnosticCode",
          "topDiagnosticSeverity",
          "topDiagnosticMessage",
          "executorDecision",
          "executorMode",
          "primaryActionName",
          "primaryReason",
          "primaryPriority",
          "primaryPriorityReason",
          "primarySourceLinkRef",
          "alternativeActionName",
          "alternativeActionExecution",
          "executorActionName",
          "executorOperation",
          "executorConfidence",
          "executorAnswerReady",
          "executorShouldContinue",
          "executorTerminal",
          "executorCommandArgs",
          "executorReadFrom",
          "executorTargetUrl",
          "executorTargetPath",
          "executorTargetSelector",
          "executorTargetText",
          "executorExpectedOutcome",
          "handoffDecision",
          "handoffMode",
          "handoffActionName",
          "handoffOperation",
          "handoffConfidence",
          "handoffAnswerReady",
          "handoffShouldContinue",
          "handoffTerminal",
          "handoffCommandArgs",
          "handoffReadFrom",
          "handoffTargetUrl",
          "handoffTargetPath",
          "handoffTargetSelector",
          "handoffTargetText",
          "handoffExpectedOutcome",
          "answerPlanStatus",
          "answerPlanConfidence",
          "answerPlanReason",
          "answerPlanNextAction",
          "answerGapCount",
          "answerUseCitationIds",
          "answerPlanReadFrom",
          "bestReadTarget",
          "bestReadTargetCount",
          "bestReadTargetPrimary",
          "recommendedUrl",
          "recommendedCommandArgs",
          "verificationFoundQueries",
          "verificationMissingQueries",
          "topVerificationFoundQuery",
          "topVerificationMissingQuery",
          "sourceSearchQuery",
          "sourceSearchEngine",
          "sourceSearchSearchUrl",
          "sourceSearchSelectedRank",
          "sourceSearchSelectedTitle",
          "sourceSearchSelectedUrl",
          "sourceSearchAlternateCount",
          "hiddenSignalCount",
          "bestHiddenReadTarget",
          "bestHiddenReadTargetCount",
          "bestHiddenReadTargetPrimary",
          "actionTargetCount",
        ]);
      },
    ),
    evidenceCheck(
      root,
      "readme-doc-split",
      "README must stay concise; long operational and agent details belong under docs/.",
      "README line limits and docs index links are enforced by tests and readiness audit.",
      (failures) => {
        checkReadmeSplit(root, failures);
        requireFileIncludes(root, failures, "tests/readme.test.ts", [
          "stays concise",
          "docs",
          "README.md",
        ]);
      },
    ),
  ];
}

if (isMainModule()) {
  const failures = checkAgentReadinessProject();
  if (failures.length > 0) {
    for (const failure of failures) {
      console.error(`${failure.file}: ${failure.message}`);
    }
    process.exit(1);
  }
  console.log(`agent-readiness: audit ok (${collectAgentReadinessEvidence().length} evidence checks)`);
}

function evidenceCheck(
  root: string,
  id: string,
  requirement: string,
  evidence: string,
  inspect: (failures: ReadinessFailure[]) => void,
): ReadinessEvidence {
  const failures: ReadinessFailure[] = [];
  inspect(failures);
  return {
    id,
    requirement,
    evidence,
    status: failures.length === 0 ? "pass" : "fail",
    failures,
  };
}

function readJson<T>(root: string, relativePath: string, failures: ReadinessFailure[]): T | undefined {
  const file = join(root, relativePath);
  if (!existsSync(file)) {
    failures.push({ file: relativePath, message: "missing file" });
    return undefined;
  }

  try {
    return JSON.parse(readFileSync(file, "utf8")) as T;
  } catch (error) {
    failures.push({ file: relativePath, message: `invalid JSON: ${String(error)}` });
    return undefined;
  }
}

function readText(root: string, relativePath: string, failures: ReadinessFailure[]): string | undefined {
  const file = join(root, relativePath);
  if (!existsSync(file)) {
    failures.push({ file: relativePath, message: "missing file" });
    return undefined;
  }
  return readFileSync(file, "utf8");
}

function requireScript(
  failures: ReadinessFailure[],
  scripts: Record<string, string>,
  name: string,
  expectedText: string,
): void {
  const value = scripts[name];
  if (typeof value === "string" && value.includes(expectedText)) return;
  failures.push({
    file: "package.json",
    message: `script ${name} must include ${JSON.stringify(expectedText)}`,
  });
}

function requireFileIncludes(
  root: string,
  failures: ReadinessFailure[],
  relativePath: string,
  requiredTexts: string[],
): void {
  const text = readText(root, relativePath, failures);
  if (typeof text !== "string") return;

  for (const requiredText of requiredTexts) {
    if (text.includes(requiredText)) continue;
    failures.push({
      file: relativePath,
      message: `missing required text ${JSON.stringify(requiredText)}`,
    });
  }
}

function checkReadmeSplit(root: string, failures: ReadinessFailure[]): void {
  const readme = readText(root, "README.md", failures);
  if (typeof readme !== "string") return;

  const lineCount = readme.trimEnd().split(/\r?\n/).length;
  if (lineCount > 80) {
    failures.push({ file: "README.md", message: `README must stay concise, got ${lineCount} lines` });
  }
  if (!readme.includes("./docs/README.md")) {
    failures.push({ file: "README.md", message: "README must link to docs/README.md" });
  }

  requireFileIncludes(root, failures, "docs/README.md", [
    "./cli-agent.md",
    "./agent-handoff.md",
    "./agent-readiness.md",
    "./benchmarks.md",
    "./comparison-baseline.md",
  ]);
}

function isMainModule(): boolean {
  const entrypoint = process.argv[1];
  if (!entrypoint) return false;
  return import.meta.url === pathToFileURL(entrypoint).href;
}
